[package]
name = "wasm-streams"
version = "0.2.2"
authors = ["Mattias Buelens <mattias@buelens.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/MattiasBuelens/wasm-streams/"
description = """
Bridging between web streams and Rust streams using WebAssembly
"""
exclude = [
    ".github/"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "^0.3.47"
wasm-bindgen = "0.2.73"
wasm-bindgen-futures = "^0.4.20"
futures-util = { version = "0.3.21", features = ["io", "sink"] }

[dependencies.web-sys]
version = "^0.3.47"
features = [
    "AbortSignal",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.20"
tokio = { version = "^1", features = ["macros", "rt"] }
pin-project = "^1.0.6"

[dev-dependencies.web-sys]
version = "^0.3.47"
features = [
    "console",
    "AbortSignal",
    "Response",
    "ReadableStream",
    "Window",
]

[package.metadata.docs.rs]
# https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html
targets = ["x86_64-unknown-linux-gnu"]
