[package]
name = "wasm-streams"
version = "0.1.1"
authors = ["Mattias Buelens <mattias@buelens.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/MattiasBuelens/wasm-streams/"
description = """
Bridging between web streams and Rust streams using WebAssembly
"""
exclude = [
    ".github/"
]

[dependencies]
js-sys = "^0.3.40"
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = "^0.4.13"
futures = "^0.3.5"

[dependencies.web-sys]
version = "^0.3.40"
features = [
    "AbortSignal",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
tokio = { version = "^0.2", features = ["macros"] }

[dev-dependencies.web-sys]
version = "^0.3.40"
features = [
    "console",
    "AbortSignal",
    "Response",
    "ReadableStream",
    "Window",
]
