[package]
name = "wasm-streams"
version = "0.1.0"
authors = ["Mattias Buelens <mattias@buelens.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "^0.3.39"
wasm-bindgen = "0.2.62"
wasm-bindgen-futures = "^0.4.12"
futures = "^0.3.5"
pin-utils = "^0.1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.12"
